# Generated by Django 6.0.3 on 2026-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_limit', models.PositiveIntegerField(default=5)),
                ('vendor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
